### ISSUE TITLE
Crashes on Start

### ISSUE THREAD

**Issue by UnknownGuardian** [Picolab/node-pico-engine#26] opened 2017-06-19 23:03 UTC
After installing rulesets on pico-engine. Pressing Ctrl + C to stop, sometimes rulesets are deleted at some point.

Last ~30 lines of console output. You can see the Ctrl + C stop, the pico-engine -h, and then re-running pico-engine.

```bash
[DEBUG] { pico_id: 'cj44qk1g0006oal7qpab6exd4',
  event: 
   { eci: 'cj44qk1g1006pal7q8nzxgyk8',
     eid: '0',
     domain: 'lab9',
     type: 'heartbeat' },
  eci: 'cj44qk1g1006pal7q8nzxgyk8' } rule added to schedule: lab9gossip -> propagationChoice
[DEBUG] { pico_id: 'cj44qk1g0006oal7qpab6exd4',
  event: 
   { eci: 'cj44qk1g1006pal7q8nzxgyk8',
     eid: '0',
     domain: 'lab9',
     type: 'heartbeat' },
  eci: 'cj44qk1g1006pal7q8nzxgyk8' } rule selected: lab9gossip -> heartbeat
[DEBUG] { rid: 'lab9gossip',
  pico_id: 'cj44qk1g0006oal7qpab6exd4',
  event: 
   { eci: 'cj44qk1g1006pal7q8nzxgyk8',
     eid: '0',
     domain: 'lab9',
     type: 'heartbeat' },
  eci: 'cj44qk1g1006pal7q8nzxgyk8' } fired
^C
matt@matt-VirtualBox:~/Documents/cs462/cs465_final_project$ pico-engine -h

USAGE

    pico-engine [--version] [--help|-h]

Environment variables
    PORT - what port the http server should listen on. By default it's 8080
    PICO_ENGINE_HOME - where the database and other files should be stored. By default it's ~/.pico-engine/

matt@matt-VirtualBox:~/Documents/cs462/cs465_final_project$ pico-engine
/usr/local/lib/node_modules/pico-engine/src/index.js:16
            throw err;
            ^

Error: keys:google not defined
    at Object.get (/usr/local/lib/node_modules/pico-engine/node_modules/pico-engine-core/src/modules/keys.js:9:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/pico-engine/node_modules/pico-engine-core/src/modules/index.js:28:33)
    at /usr/local/lib/node_modules/pico-engine/node_modules/co-callback/index.js:36:20
    at Object.get (/usr/local/lib/node_modules/pico-engine/node_modules/co-callback/index.js:31:20)
    at with (/home/matt/.pico-engine/rulesets/0.29.8-0.31.5/06/3c/063cbf0738b6a156d33893b47b060a0f6c38a76435f27a3049a060699cf133bf.js:19:61)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/pico-engine/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/pico-engine/node_modules/co/index.js:54:5
    at co (/usr/local/lib/node_modules/pico-engine/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/pico-engine/node_modules/co/index.js:118:63)
matt@matt-VirtualBox:~/Documents/cs462/cs465_final_project$ 
```

Only solution is deleting folder .pico-engine, then re-installing everything. This has happened twice already with the current setup I have. I'll provide files if you want.

**Comment by 0joshuaolson1** [comment] 2017-07-25 16:39
>I'll provide files if you want.

Yes, please.

**Comment by 0joshuaolson1** [comment] 2017-09-26 19:34
Closing as cannot reproduce.

**Closed by 0joshuaolson1** 2017-09-26 19:34 UTC
